import os


class Config:
    # ELASTICSEARCH_URL = os.getenv("ELASTICSEARCH_URL")
    # ELASTICSEARCH_USERNAME = os.getenv("ELASTICSEARCH_USERNAME")
    # ELASTICSEARCH_PASSWORD = os.getenv("ELASTICSEARCH_PASSWORD")
    
    ELASTICSEARCH_URL = "https://localhost:9200"
    ELASTICSEARCH_USERNAME = "elastic"
    ELASTICSEARCH_PASSWORD = "WJv7nau2OS=JRJyW8XXe"