import os


class Config:
    ELASTICSEARCH_URL = os.getenv("ELASTICSEARCH_URL")
    ELASTICSEARCH_USERNAME = os.getenv("ELASTICSEARCH_USERNAME")
    ELASTICSEARCH_PASSWORD = os.getenv("ELASTICSEARCH_PASSWORD")